events {
    worker_connections 1024;
}

http {
    server {
        # Слушаем 80 порт, который будет доступен с хост-машины
        listen 80;
        server_name localhost;

        # Блок обработки всех запросов
        location / {
            # Запросы перенаправляются на сервис с именем 'server'
            # на порт 8000. Имя 'server' берется из docker-compose.yml
            proxy_pass http://server:8000;

            # Важные заголовки для передачи реальной информации о клиенте
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}